#!/usr/bin/env python
import io
import sys

import numpy as np
from PIL import Image, ImageChops
from pypdf import PdfReader

reader = PdfReader(sys.argv[1])

page = reader.pages[0]
img = page.images[1].data
# Read as grayscale
_img = Image.open(io.BytesIO(img)).convert('L')
# Invert colors (background as zero in NumPy)
img = ImageChops.invert(_img)

first_sig = img.crop((25, 1880, 400, 2079))

first_sig.show()
arr = np.array(first_sig)
print(arr.shape, arr.mean())
print(arr)


