[project]
name = "pdf-recognition"
version = "0.1.0"
description = "Identify whether PDF files contain signatures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython",
    "numpy",
    "pandas",
    "pillow",
    "pypdf[image]",
    "pyyaml",
]
